# coding=utf-8

# MSG_ID = "F1TENTH-VAUL"
# MSG_ID = "R2S2R-project"
# MSG_ID = "♞"
# MSG_ID = "♣︎"
# MSG_ID = "⸭"
# MSG_ID = "❦"
MSG_ID = "𝔖"
# MSG_ID = "𝕾"
# MSG_ID = "❡"
# MSG_ID = "𝜋"
# MSG_ID = "☆"
# MSG_ID = "♜"
# MSG_ID = "🚩"
# MSG_ID = "🏴"
# MSG_ID = "🌬"
# MSG_ID = "🅰"
# MSG_ID = "❄︎"
# MSG_ID = "❇︎"

# MSG_SEP = " "
MSG_SEP = ""
# MSG_SEP = "|"
MSG_SEP = "⟩"
# MSG_SEP = "▶︎"
# MSG_OPEN_CHAR = ""
MSG_OPEN_CHAR = "["
# MSG_OPEN_CHAR = "▍"
MSG_CLOSE_CHAR = "]"
# MSG_CLOSE_CHAR = f" {MSG_SEP}"

# MSG_PREFIX = f"{MSG_ID}"
MSG_PREFIX = f"{MSG_ID}{MSG_SEP} "
# MSG_PREFIX = f"{MSG_ID}{MSG_SEP}"
